=== luki122/simpe/tags/SimPE_0_65_1/fullsimpe/__Data/tgi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von F. Bauer (Privat) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von F. Bauer (Privat) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="idType">
		<xs:restriction base="xs:ID">
			<xs:pattern value="[0-9a-fA-F]{1,8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="tgi">
		<xs:annotation>
			<xs:documentation>Container for all Type Definitions</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="type" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name"/>
							<xs:element name="shortname"/>
							<xs:element name="extension" minOccurs="0"/>
							<xs:element name="known" minOccurs="0"/>
							<xs:element name="embeddedfilename" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="value" use="required">
							<xs:simpleType>
								<xs:restriction base="idType">
									<xs:whiteSpace value="collapse"/>
									<xs:maxLength value="8"/>
									<xs:minLength value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== luki122/simpe/__Release/Data/tgi.xml
<?xml version="1.0" encoding="utf-8"?>
<tgi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tgi.xsd">
	<type value="FFFFFFFF">
		<name>--- User Defined ---</name>
		<shortname>----</shortname>
	</type>
	<type value="61754C1B"> 
		<name>SimPE Object Lua</name>
		<shortname>SLUA</shortname>
		<known/>
		<embeddedfilename/>
		<!-- This is a SimPE Custom Format! And is now obsolete since Maxis introduced their own LUA .packahe Formats-->
	</type>
	<type value="ABD0DC63">
		<name>Neighborhood Terrain</name>
		<shortname>NHTR</shortname>
		<known/>
	</type>
	<type value="104F6A6E">
		<name>Business Info</name>
		<shortname>BNFO</shortname>
		<known/>
	</type>
	<type value="CDB467B8">
		<name>Content Registry</name>
		<shortname>CREG</shortname>
		<known/>
	</type>
	<type value="4F6FD33D">
		<name>Inventory Item</name>
		<shortname>INIT</shortname>
		<known/>
	</type>
        <type value="3053CF74"> 
		<name>Sim: Scores</name>
		<shortname>SCOR</shortname>
		<known/>
	</type>
	<type value="9012468B"> 
		<name>Object Lua</name>
		<shortname>OLUA</shortname>
		<known/>
	</type>
	<type value="9012468A"> 
		<name>Global Object Lua</name>
		<shortname>GLUA</shortname>
		<known/>
	</type>
	<type value="ABCB5DA4">
		<name>Neighborhood Terrain Geometry</name>
		<shortname>NHTG</shortname>
		<known/>
	</type>
	<type value="6B943B43">
		<name>Lot Terrain Geometry</name>
		<shortname>LOTG</shortname>
		<known/>
	</type>
	<type value="2A51171B">
		<name>3D Array</name>
		<shortname>3ARY</shortname>
		<known/>
	</type>
	<type value="AC598EAC">
		<name>Age Data</name>
		<shortname>AGED</shortname>
		<known/>
	</type>
	<type value="FB00791E">
		<name>Animation Resource</name>
		<shortname>ANIM</shortname>
		<extension>5an</extension>
		<known/>
	</type>
	<type value="EBFEE345">
		<name>Audio Test</name>
		<shortname>AUDT</shortname>
		<known/>
	</type>
	<type value="42434F4E">
		<name>Behaviour Constant</name>
		<shortname>BCON</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="42484156">
		<name>Behaviour Function</name>
		<shortname>BHAV</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="0C560F39">
		<name>Binary Index</name>
		<shortname>BINX</shortname>
		<known/>
	</type>
	<type value="424D505F">
		<name>Bitmap Image</name>
		<shortname>BMP</shortname>
		<extension>bmp</extension>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="43415453">
		<name>Catalog String</name>
		<shortname>CATS</shortname>
		<known/>
	</type>
	<type value="6C4F359D">
		<name>Collection</name>
		<shortname>COLL</shortname>
		<known/>
	</type>
	<type value="E519C933">
		<name>Resource Node</name>
		<shortname>CRES</shortname>
		<extension>5cr</extension>
		<known/>
	</type>
	<type value="43545353">
		<name>Catalog Description</name>
		<shortname>CTSS</shortname>
		<known/>
	</type>
	<type value="CCCEF852">
		<name>Facial Structure</name>
		<shortname>LxNR</shortname>
		<known/>
	</type>
	<type value="44475250">
		<name>Layered Image</name>
		<shortname>DGRP</shortname>
		<known/>
	</type>
	<type value="EA5118B0">
		<name>Effects List</name>
		<shortname>FX</shortname>
		<extension>fx</extension>
		<known/>
	</type>
	<type value="46414345">
		<name>Face Properties</name>
		<shortname>FACE</shortname>
		<known/>
	</type>
	<type value="46414D49">
		<name>Family Information</name>
		<shortname>FAMI</shortname>
		<known/>
	</type>
	<type value="46434E53">
		<name>Function</name>
		<shortname>FCNS</shortname>
		<known/>
	</type>
	<type value="CD95548E">
		<name>Sim Wants and Fears</name>
		<shortname>SWAF</shortname>
		<known/>
	</type>
	<type value="AB4BA572">
		<name>Fence Post Layer</name>
		<shortname>FPST</shortname>
		<known/>
	</type>
	<type value="46574156">
		<name>Audio Reference</name>
		<shortname>FWAV</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="8DB5E4C2">
		<name>FX Sound</name>
		<shortname>FXSD</shortname>
		<known/>
	</type>
	<type value="474C4F42">
		<name>Global Data</name>
		<shortname>GLOB</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="AC4F8687">
		<name>Geometric Data Container</name>
		<shortname>GMDC</shortname>
		<extension>5gd</extension>
		<known/>
	</type>
	<type value="7BA3838C">
		<name>Geometric Node</name>
		<shortname>GMND</shortname>
		<extension>5gn</extension>
		<known/>
	</type>
	<type value="EBCF3E27">
		<name>Property Set</name>
		<shortname>GZPS</shortname>
		<known/>
	</type>
	<type value="484F5553">
		<name>House Descriptor</name>
		<shortname>HOUS</shortname>
		<known/>
	</type>
	<type value="AC8A7A2E">
		<name>ID Number</name>
		<shortname>IDNO</shortname>
		<known/>
	</type>
	<type value="0C7E9A76">
		<name>JPEG Image</name>
		<shortname>JPG</shortname>
		<extension>jpg</extension>
		<known/>
	</type>
	<type value="4D533EDD">
		<name>JPEG Image</name>
		<shortname>JPG</shortname>
		<extension>jpg</extension>
		<known/>
	</type>
	<type value="8C3CE95A">
		<name>JPEG Image</name>
		<shortname>JPG</shortname>
		<extension>jpg</extension>
		<known/>
	</type>
	<type value="856DDBAC">
		<name>jpg/tga/png Image</name>
		<shortname>IMG</shortname>
		<extension>jpg</extension>
		<known/>
	</type>
	<type value="C9C81BA3">
		<name>Lighting (Ambient Light)</name>
		<shortname>LGHT</shortname>
		<extension>5al</extension>
		<known/>
	</type>
	<type value="C9C81B9B">
		<name>Lighting (Directional Light)</name>
		<shortname>LGHT</shortname>
		<extension>5dl</extension>
		<known/>
	</type>
	<type value="C9C81BA9">
		<name>Lighting (Point Light)</name>
		<shortname>LGHT</shortname>
		<extension>5pl</extension>
		<known/>
	</type>
	<type value="C9C81BAD">
		<name>Lighting (Spot Light)</name>
		<shortname>LGHT</shortname>
		<extension>5sl</extension>
		<known/>
	</type>
	<type value="AC06A676">
		<name>Lighting (Draw State Light)</name>
		<shortname>LGHT</shortname>
		<extension>5ds</extension>
		<known/>
	</type>
	<type value="6A97042F">
		<name>Lighting (Environment Cube Light)</name>
		<shortname>LGHT</shortname>
		<extension>5el</extension>
		<known/>
	</type>
	<type value="AC06A66F">
		<name>Lighting (Linear Fog Light)</name>
		<shortname>LGHT</shortname>
		<extension>5lf</extension>
		<known/>
	</type>
	<type value="ED534136">
		<name>Large Image File</name>
		<shortname>LIFO</shortname>
		<extension>6li</extension>
		<known/>
	</type>
	<type value="4E6D6150">
		<name>Name Map</name>
		<shortname>NMAP</shortname>
		<known/>
	</type>
	<type value="E86B1EEF">
		<name>Directory of Compressed Files</name>
		<shortname>CLST</shortname>
		<extension>dir</extension>
		<known/>
	</type>
	<type value="0BF999E7">
		<name>Lot Description</name>
		<shortname>LTXT</shortname>
		<known/>
	</type>
	<type value="4B58975B">
		<name>Lot Texture</name>
		<shortname>LTTX</shortname>
		<known/>
	</type>
	<type value="49596978">
		<name>Material Definition</name>
		<shortname>TXMT</shortname>
		<extension>5tm</extension>
		<known/>
	</type>
	<type value="4C697E5A">
		<name>Material Override</name>
		<shortname>MMAT</shortname>
		<known/>
	</type>
	<type value="4E474248">
		<name>Neighborhood/Memory</name>
		<shortname>NGBH</shortname>
		<known/>
	</type>
	<type value="4E524546">
		<name>Name Reference</name>
		<shortname>NREF</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="4F424A44">
		<name>Object Data</name>
		<shortname>OBJD</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="4F424A66">
		<name>Object Functions</name>
		<shortname>OBJf</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="4F626A4D">
		<name>Object Material?</name>
		<shortname>OBJM</shortname>
		<known/>
	</type>
	<type value="6F626A74">
		<name>Object</name>
		<shortname>OBJT</shortname>
		<known/>
	</type>
	<type value="FA1C39F7">
		<name>Object</name>
		<shortname>OBJT</shortname>
		<known/>
	</type>
	<type value="50414C54">
		<name>Image Color Palette (Version 1)</name>
		<shortname>PALT</shortname>
		<known/>
	</type>
	<type value="AC506764">
		<name>3D ID Referencing File</name>
		<shortname>3IDR</shortname>
		<known/>
	</type>
	<type value="504F5349">
		<name>Stack Script</name>
		<shortname>POSI</shortname>
		<known/>
	</type>
	<type value="CD7FE87A">
		<name>Maxis Material Shader</name>
		<shortname>MATSHAD</shortname>
		<extension>matshad</extension>
		<known/>
	</type>
	<type value="50544250">
		<name>Package Text</name>
		<shortname>PTBP</shortname>
		<known/>
	</type>
	<type value="ACE46235">
		<name>Road Texture</name>
		<shortname>RTEX</shortname>
		<known/>
	</type>
	<type value="8CC0A14B">
		<name>UNK: 0x8CC0A14B</name>
		<shortname>SDBA</shortname>
	</type>
	<type value="EBFEE33F">
		<name>Sim DNA</name>
		<shortname>SDNA</shortname>
		<known/>
	</type>
	<type value="FC6EB1F7">
		<name>Shape</name>
		<shortname>SHPE</shortname>
		<extension>5sh</extension>
		<known/>
	</type>
	<type value="53494D49">
		<name>Sim Information</name>
		<shortname>SIMI</shortname>
		<known/>
	</type>
	<type value="534C4F54">
		<name>Slot File</name>
		<shortname>SLOT</shortname>
		<embeddedfilename/>
	</type>
	<type value="CAC4FC40">
		<name>String Map</name>
		<shortname>SMAP</shortname>
		<known/>
	</type>
	<type value="53505232">
		<name>Sprites</name>
		<shortname>SPR2</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="2026960B">
		<name>mp3 or xa Sound File</name>
		<shortname>MP3</shortname>
		<extension>mp3</extension>
		<known/>
	</type>
	<type value="53545223">
		<name>Text Lists</name>
		<shortname>STR#</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="54415454">
		<name>TATT</name>		
		<shortname>TATT</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="54505250">
		<name>Edith Simantics Behaviour Labels</name>
		<shortname>TPRP</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="54524545">
		<name>Edith Flowchart Trees</name>
		<shortname>TREE</shortname>
		<known/>
		<embeddedfilename/>
	</type>
	<type value="0B9EB87E">
