=== luki122/simpe/__Data/propertydefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von F. Bauer (Privat) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von F. Bauer (Privat) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von F. Bauer (Privat) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von F. Bauer (Privat) -->
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Frank Bauer (Privat) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:attribute name="type" type="xs:NMTOKEN"/>
	<xs:complexType name="PropertyType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="help" type="xs:string" minOccurs="0"/>
			<xs:element name="default" type="xs:string"/>
			<xs:element name="min" type="xs:string" minOccurs="0"/>
			<xs:element name="max" type="xs:string" minOccurs="0"/>
			<xs:element name="readonly" minOccurs="0"/>
			<xs:element name="index" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:unsignedInt">
							<xs:attribute name="type" type="xs:unsignedShort" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute ref="type" use="required"/>
	</xs:complexType>
	<xs:element name="properties">
		<xs:annotation>
			<xs:documentation>Lists all known Properties for TXMT Files</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="enum" minOccurs="0" maxOccurs="32">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="field" maxOccurs="256">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="value" type="xs:int" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="writeas" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="name"/>
									<xs:enumeration value="value"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="category" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="property" type="PropertyType" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== luki122/simpe/fullsimpe/__Release/Data/objddefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<properties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="propertydefinition.xsd">
	<!-- ****************************************************************************** -->
	<category name="Placement">
		<property type="short">
			<name>Default Wall Adjacent Flags</name>
			<help>Default Wall Adjacent Flags</help>
			<default>0</default>
			<index type="0">3</index>
			<index type="2">3</index>
			<index type="4">3</index>
			<index type="5">3</index>
			<index type="7">3</index>
			<index type="8">3</index>
			<index type="9">3</index>
			<index type="10">3</index>
			<index type="11">3</index>
			<index type="14">3</index>
			<index type="15">3</index>
			<index type="16">3</index>
		</property>
		<property type="short">
			<name>Default Allowed Height Flags</name>
			<help>Default Allowed Height Flags</help>
			<default>0</default>
			<index type="0">6</index>
			<index type="2">6</index>
			<index type="4">6</index>
			<index type="5">6</index>
			<index type="7">6</index>
			<index type="8">6</index>
			<index type="9">6</index>
			<index type="10">6</index>
			<index type="11">6</index>
			<index type="14">6</index>
			<index type="15">6</index>
			<index type="16">6</index>
		</property>
		<property type="short">
			<name>Multi-Tile master id</name>
			<help>Multi-Tile master id</help>
			<default>0</default>
			<index type="0">10</index>
			<index type="2">10</index>
			<index type="4">10</index>
			<index type="5">10</index>
			<index type="7">10</index>
			<index type="8">10</index>
			<index type="9">10</index>
			<index type="10">10</index>
			<index type="11">10</index>
			<index type="14">10</index>
			<index type="15">10</index>
			<index type="16">10</index>
		</property>
		<property type="short">
			<name>front direction</name>
			<help>front direction</help>
			<default>0</default>
			<index type="0">61</index>
			<index type="2">61</index>
			<index type="4">61</index>
			<index type="5">61</index>
			<index type="7">61</index>
			<index type="8">61</index>
			<index type="9">61</index>
			<index type="10">61</index>
			<index type="11">61</index>
			<index type="12">61</index>
			<index type="13">61</index>
			<index type="14">61</index>
			<index type="15">61</index>
			<index type="16">61</index>
		</property>
		<property type="short">
			<name>chair entry flags</name>
			<help>chair entry flags</help>
			<default>0</default>
			<index type="0">66</index>
			<index type="2">66</index>
			<index type="4">66</index>
			<index type="5">66</index>
			<index type="7">66</index>
			<index type="8">66</index>
			<index type="9">66</index>
			<index type="10">66</index>
			<index type="11">66</index>
			<index type="12">66</index>
			<index type="13">66</index>
			<index type="14">66</index>
			<index type="15">66</index>
			<index type="16">66</index>
		</property>
		<property type="short">
			<name>Multi-Tile sub index</name>
			<help>Multi-Tile sub index</help>
			<default>0</default>
			<index type="0">11</index>
			<index type="2">11</index>
			<index type="4">11</index>
			<index type="5">11</index>
			<index type="7">11</index>
			<index type="8">11</index>
			<index type="9">11</index>
			<index type="10">11</index>
			<index type="11">11</index>
			<index type="14">11</index>
			<index type="15">11</index>
			<index type="16">11</index>
		</property>
		<property type="short">
			<name>tile width</name>
			<help>tile width</help>
			<default>0</default>
			<index type="0">67</index>
			<index type="2">67</index>
			<index type="4">67</index>
			<index type="5">67</index>
			<index type="7">67</index>
			<index type="8">67</index>
			<index type="9">67</index>
			<index type="10">67</index>
			<index type="11">67</index>
			<index type="12">67</index>
			<index type="13">67</index>
			<index type="14">67</index>
			<index type="15">67</index>
			<index type="16">67</index>
		</property>
		<property type="short">
			<name>Use Default Placement flags</name>
			<help>Use Default Placement flags</help>
			<default>0</default>
			<index type="0">12</index>
			<index type="2">12</index>
			<index type="4">12</index>
			<index type="5">12</index>
			<index type="7">12</index>
			<index type="8">12</index>
			<index type="9">12</index>
			<index type="10">12</index>
			<index type="11">12</index>
			<index type="14">12</index>
			<index type="15">12</index>
			<index type="16">12</index>
		</property>
		<property type="short">
			<name>Default Placement Flags</name>
			<help>Default Placement Flags</help>
			<default>0</default>
			<index type="0">4</index>
			<index type="2">4</index>
			<index type="4">4</index>
			<index type="5">4</index>
			<index type="7">4</index>
			<index type="8">4</index>
			<index type="9">4</index>
			<index type="10">4</index>
			<index type="11">4</index>
			<index type="14">4</index>
			<index type="15">4</index>
			<index type="16">4</index>
		</property>
		<property type="short">
			<name>Multi-Tile lead object</name>
			<help>Multi-Tile lead object</help>
			<default>0</default>
			<index type="0">63</index>
			<index type="2">63</index>
			<index type="4">63</index>
			<index type="5">63</index>
			<index type="7">63</index>
			<index type="8">63</index>
			<index type="9">63</index>
			<index type="10">63</index>
			<index type="11">63</index>
			<index type="14">63</index>
			<index type="15">63</index>
			<index type="16">63</index>
		</property>
		<property type="short">
			<name>Default Wall Placement Flags</name>
			<help>Default Wall Placement Flags</help>
			<default>0</default>
			<index type="0">5</index>
			<index type="2">5</index>
			<index type="4">5</index>
			<index type="5">5</index>
			<index type="7">5</index>
			<index type="8">5</index>
			<index type="9">5</index>
			<index type="10">5</index>
			<index type="11">5</index>
			<index type="14">5</index>
			<index type="15">5</index>
			<index type="16">5</index>
		</property>
		<property type="short">
			<name>No Duplicate On Placement</name>
			<help>No Duplicate On Placement</help>
			<default>0</default>
			<index type="0">46</index>
			<index type="2">46</index>
			<index type="4">46</index>
			<index type="5">46</index>
			<index type="7">46</index>
			<index type="8">46</index>
			<index type="9">46</index>
			<index type="10">46</index>
			<index type="11">46</index>
			<index type="14">46</index>
			<index type="15">46</index>
			<index type="16">46</index>
		</property>
	</category>
	<!-- ****************************************************************************** -->
	<category name="Mesh &amp; Graphics">
		<property type="short">
			<name>level offset</name>
			<help>level offset</help>
			<default>0</default>
			<index type="0">56</index>
			<index type="2">56</index>
			<index type="4">56</index>
			<index type="5">56</index>
			<index type="7">56</index>
			<index type="8">56</index>
			<index type="9">56</index>
			<index type="10">56</index>
			<index type="11">56</index>
			<index type="12">56</index>
			<index type="13">56</index>
			<index type="14">56</index>
			<index type="15">56</index>
			<index type="16">56</index>
		</property>
		<property type="short">
			<name>shadow</name>
			<help>shadow</help>
			<default>0</default>
			<index type="12">57</index>
			<index type="13">57</index>
		</property>
		<property type="short">
			<name>Unused - thumbnail graphic (Sims1)</name>
			<help>Unused - thumbnail graphic (Sims1)</help>
			<default>0</default>
			<index type="0">75</index>
			<index type="2">75</index>
			<index type="4">75</index>
			<index type="5">75</index>
			<index type="7">75</index>
			<index type="8">75</index>
			<index type="9">75</index>
			<index type="10">75</index>
			<index type="11">75</index>
			<index type="14">75</index>
			<index type="15">75</index>
			<index type="16">75</index>
			<index type="12">75</index>
			<index type="13">75</index>
		</property>
		<property type="short">
			<name>Unused - shadow flags (Sims1)</name>
			<help>Unused - shadow flags (Sims1)</help>
			<default>0</default>
			<index type="0">76</index>
			<index type="2">76</index>
			<index type="4">76</index>
			<index type="5">76</index>
			<index type="7">76</index>
			<index type="8">76</index>
			<index type="9">76</index>
			<index type="10">76</index>
			<index type="11">76</index>
			<index type="14">76</index>
			<index type="15">76</index>
			<index type="16">76</index>
			<index type="12">76</index>
			<index type="13">76</index>
		</property>
		<property type="short">
			<name>base graphic</name>
			<help>base graphic</help>
			<default>0</default>
			<index type="12">3</index>
			<index type="13">3</index>
		</property>
		<property type="short">
			<name>3D Object Type</name>
			<help>3D Object Type</help>
			<default>0</default>
			<index type="0">99</index>
			<index type="2">99</index>
			<index type="4">99</index>
			<index type="5">99</index>
			<index type="7">99</index>
			<index type="8">99</index>
			<index type="9">99</index>
			<index type="10">99</index>
			<index type="11">99</index>
			<index type="14">99</index>
			<index type="15">99</index>
			<index type="16">99</index>
		</property>
		<property type="short">
			<name>shadow type</name>
			<help>shadow type</help>
			<default>0</default>
			<index type="0">57</index>
			<index type="2">57</index>
			<index type="4">57</index>
			<index type="5">57</index>
			<index type="7">57</index>
			<index type="8">57</index>
			<index type="9">57</index>
			<index type="10">57</index>
			<index type="11">57</index>
			<index type="14">57</index>
			<index type="15">57</index>
			<index type="16">57</index>
		</property>
		<property type="short">
			<name>Unused - shadow brightness (Sims1)</name>
			<help>Unused - shadow brightness (Sims1)</help>
			<default>0</default>
			<index type="0">79</index>
			<index type="2">79</index>
			<index type="4">79</index>
			<index type="5">79</index>
			<index type="7">79</index>
